from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import (user_login, 
                    admin_dashboard, 
                    staff_dashboard, 
                    employee_dashboard, 
                    researcher_dashboard, 
                    comparacion_algoritmos_dashboard,
                    admin_map_dashboard, 
                    guardar_poligono_colonia, 
                    cargar_colonia_existente, 
                    buscar_colonia_inteligente,
                    admin_user_control,
                    procesar_usuarios_masivos,
                    cargar_colonia_staff,
                    guardar_configuracion_rutas,
                    listar_rutas_staff,
                    dividir_poligono_para_empleados,
                    consultar_rutas_staff,
                    obtener_mapa_calculado,
                    enviar_rutas_por_email,
                    enviar_rutas_desde_dashboard,
                    obtener_ruta_empleado,
                    obtener_mensajes_chat,
                    enviar_mensaje_chat,
                    verificar_mensajes_nuevos,
                    chat_dashboard,
                    user_logout,
                    researcher_dashboard,
                    analizar_algoritmo,
                    comparar_algoritmos,
                    obtener_historico_algoritmo,
                    gestion_algoritmos_dashboard,
                    cambiar_algoritmo_defecto,
                    visualizar_ruta,
                    random_forest_dashboard,
                    entrenar_modelo_random_forest,
                    predecir_tiempo_random_forest,
                    obtener_estadisticas_random_forest,
                    marcar_ruta_completada,
                    marcar_ruta_completada_staff,
                    obtener_rutas_empleado,
                    obtener_rutas_staff_supervision,
                    get_all_colonias)

urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path('staff_dashboard/', staff_dashboard, name='staff_dashboard'),
    path('employee_dashboard/', employee_dashboard, name='employee_dashboard'),
    path('researcher_dashboard/', researcher_dashboard, name='researcher_dashboard'),
    path('admin_map_dashboard/', admin_map_dashboard, name='admin_map_dashboard'),
    path('guardar_poligono/', guardar_poligono_colonia, name='guardar_poligono_colonia'),
    path('cargar_colonia/', cargar_colonia_existente, name='cargar_colonia_existente'),
    path('buscar_colonia_inteligente/', buscar_colonia_inteligente, name='buscar_colonia_inteligente'),
    path('admin_user_control/', admin_user_control, name='admin_user_control'),
    path('procesar_usuarios_masivos/', procesar_usuarios_masivos, name='procesar_usuarios_masivos'),
    path('cargar_colonia_staff/', cargar_colonia_staff, name='cargar_colonia_staff'),
    path('guardar_configuracion_rutas/', guardar_configuracion_rutas, name='guardar_configuracion_rutas'),
    path('listar_rutas_staff/', listar_rutas_staff, name='listar_rutas_staff'),
    path('dividir_poligono_para_empleados/', dividir_poligono_para_empleados, name='dividir_poligono_para_empleados'),
    path('consultar_rutas/', consultar_rutas_staff, name='consultar_rutas_staff'),
    path('obtener_mapa_calculado/', obtener_mapa_calculado, name='obtener_mapa_calculado'),
    path('enviar_rutas_por_email/', enviar_rutas_por_email, name='enviar_rutas_por_email'),
    path('enviar_rutas_desde_dashboard/', enviar_rutas_desde_dashboard, name='enviar_rutas_desde_dashboard'),
    path('obtener_ruta_empleado/', obtener_ruta_empleado, name='obtener_ruta_empleado'),
    
    # URLs del sistema de chat
    path('chat/obtener_mensajes/', obtener_mensajes_chat, name='obtener_mensajes_chat'),
    path('chat/enviar_mensaje/', enviar_mensaje_chat, name='enviar_mensaje_chat'),
    path('chat/verificar_nuevos/', verificar_mensajes_nuevos, name='verificar_mensajes_nuevos'),
    
    # Dashboard de chats del staff
    path('chat_dashboard/', chat_dashboard, name='chat_dashboard'),
    
    # Logout
    path('logout/', user_logout, name='user_logout'),
    
    # URLs del researcher
    path('researcher_dashboard/', researcher_dashboard, name='researcher_dashboard'),
    path('comparacion_algoritmos/', comparacion_algoritmos_dashboard, name='comparacion_algoritmos_dashboard'),
    path('api/analizar_algoritmo/', analizar_algoritmo, name='analizar_algoritmo'),
    path('api/comparar_algoritmos/', comparar_algoritmos, name='comparar_algoritmos'),
    path('api/obtener_historico/', obtener_historico_algoritmo, name='obtener_historico_algoritmo'),
    path('gestion_algoritmos/', gestion_algoritmos_dashboard, name='gestion_algoritmos_dashboard'),
    path('api/cambiar_algoritmo_defecto/', cambiar_algoritmo_defecto, name='cambiar_algoritmo_defecto'),
    path('api/visualizar_ruta/', visualizar_ruta, name='visualizar_ruta'),
    
    # URLs de Random Forest
    path('random_forest/', random_forest_dashboard, name='random_forest_dashboard'),
    path('api/entrenar_modelo_rf/', entrenar_modelo_random_forest, name='entrenar_modelo_random_forest'),
    path('api/predecir_tiempo_rf/', predecir_tiempo_random_forest, name='predecir_tiempo_random_forest'),
    path('api/estadisticas_rf/', obtener_estadisticas_random_forest, name='obtener_estadisticas_random_forest'),

    # URLs de Marcado de Rutas Completadas
    path('api/marcar_ruta_completada/', marcar_ruta_completada, name='marcar_ruta_completada'),
    path('api/marcar_ruta_completada_staff/', marcar_ruta_completada_staff, name='marcar_ruta_completada_staff'),
    path('api/rutas_empleado/', obtener_rutas_empleado, name='obtener_rutas_empleado'),
    path('api/rutas_staff_supervision/', obtener_rutas_staff_supervision, name='obtener_rutas_staff_supervision'),
    path('get_all_colonias/', get_all_colonias, name='get_all_colonias'),
]