from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import (user_login, 
                    admin_dashboard, 
                    staff_dashboard, 
                    employee_dashboard, 
                    researcher_dashboard, 
                    admin_map_dashboard, 
                    guardar_poligono_colonia, 
                    cargar_colonia_existente, 
                    admin_user_control,
                    procesar_usuarios_masivos,
                    cargar_colonia_staff,
                    guardar_configuracion_rutas,
                    listar_rutas_staff,
                    dividir_poligono_para_empleados,
                    consultar_rutas_staff,
                    obtener_mapa_calculado,
                    enviar_rutas_por_email,
                    enviar_rutas_desde_dashboard)

urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path('staff_dashboard/', staff_dashboard, name='staff_dashboard'),
    path('employee_dashboard/', employee_dashboard, name='employee_dashboard'),
    path('researcher_dashboard/', researcher_dashboard, name='researcher_dashboard'),
    path('admin_map_dashboard/', admin_map_dashboard, name='admin_map_dashboard'),
    path('guardar_poligono/', guardar_poligono_colonia, name='guardar_poligono_colonia'),
    path('cargar_colonia/', cargar_colonia_existente, name='cargar_colonia_existente'),
    path('admin_user_control/', admin_user_control, name='admin_user_control'),
    path('procesar_usuarios_masivos/', procesar_usuarios_masivos, name='procesar_usuarios_masivos'),
    path('cargar_colonia_staff/', cargar_colonia_staff, name='cargar_colonia_staff'),
    path('guardar_configuracion_rutas/', guardar_configuracion_rutas, name='guardar_configuracion_rutas'),
    path('listar_rutas_staff/', listar_rutas_staff, name='listar_rutas_staff'),
    path('dividir_poligono_para_empleados/', dividir_poligono_para_empleados, name='dividir_poligono_para_empleados'),
    path('consultar_rutas/', consultar_rutas_staff, name='consultar_rutas_staff'),
    path('obtener_mapa_calculado/', obtener_mapa_calculado, name='obtener_mapa_calculado'),
    path('enviar_rutas_por_email/', enviar_rutas_por_email, name='enviar_rutas_por_email'),
    path('enviar_rutas_desde_dashboard/', enviar_rutas_desde_dashboard, name='enviar_rutas_desde_dashboard'),
]