# Generated by Django 5.2.1 on 2025-07-20 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoniaProcesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('nombre_normalizado', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='colonias/imagenes/')),
                ('poligono_geojson', models.JSONField(blank=True, null=True)),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('configuracion', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colonia Procesada',
                'verbose_name_plural': 'Colonias Procesadas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
