# Generated by Django 5.2.1 on 2025-07-21 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion_empleados', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('datos_ruta', models.JSONField(blank=True, null=True)),
                ('mapa_calculado', models.JSONField(blank=True, null=True)),
                ('chat_asignado', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempo_calculado', models.DurationField(blank=True, null=True)),
                ('tiempo_de_asignacion', models.DateTimeField(auto_now_add=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_rutas', to='core.coloniaprocesada')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleados_asignados', models.ManyToManyField(limit_choices_to={'role': 'employee'}, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Ruta',
                'verbose_name_plural': 'Configuraciones de Rutas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
