# Generated by Django 5.2.1 on 2025-07-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_mapa_html_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionruta',
            name='mapa_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
