# Generated by Django 5.0.6 on 2025-08-09 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracionruta_mapa_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo_mensaje', models.CharField(choices=[('texto', 'Mensaje de Texto'), ('sistema', 'Mensaje del Sistema'), ('ubicacion', 'Compartir Ubicación'), ('rapido', 'Mensaje Rápido')], default='texto', max_length=20)),
                ('es_leido', models.BooleanField(default=False)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('configuracion_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='core.configuracionruta')),
                ('mensaje_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.chatmessage')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_visto', models.DateTimeField(auto_now_add=True)),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('rol_en_chat', models.CharField(choices=[('staff', 'Staff'), ('empleado', 'Empleado')], max_length=20)),
                ('configuracion_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_chat', to='core.configuracionruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de Chat',
                'verbose_name_plural': 'Participantes de Chat',
                'unique_together': {('configuracion_ruta', 'usuario')},
            },
        ),
    ]
