# Generated by Django 5.2.1 on 2025-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_eficiencia_algoritmica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eficienciaalgoritmica',
            name='algoritmo_tipo',
            field=models.CharField(choices=[('kernighan_lin', 'Kernighan-Lin'), ('current', 'Kernighan-Lin (Current)'), ('kmeans', 'K-Means Clustering'), ('voronoi', 'Voronoi Diagram'), ('random', 'Random Division'), ('dbscan', 'DBSCAN Clustering'), ('spectral', 'Spectral Clustering')], max_length=20),
        ),
    ]
