# Generated by Django 5.0.6 on 2025-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_eficienciaalgoritmica_algoritmo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficienciaalgoritmica',
            name='silhouette_score',
            field=models.FloatField(default=0.0, help_text='Silhouette Score para evaluar calidad del clustering (-1 a 1)'),
        ),
    ]
