# Generated by Django 5.0.6 on 2025-08-15 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eficienciaalgoritmica_silhouette_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlgoritmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo_por_defecto', models.CharField(choices=[('kernighan_lin', 'Kernighan-Lin'), ('kmeans', 'K-Means Clustering'), ('dbscan', 'DBSCAN Clustering'), ('spectral', 'Spectral Clustering'), ('voronoi', 'Voronoi Diagram'), ('random', 'División Aleatoria')], default='kernighan_lin', help_text='Algoritmo que se usará por defecto en el sistema', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de por qué se eligió este algoritmo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó el último cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Algoritmo',
                'verbose_name_plural': 'Configuraciones de Algoritmos',
            },
        ),
    ]
