# Generated by Django 4.2.7 on 2025-08-26 20:19

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_configuracionalgoritmo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionruta',
            name='algoritmo_usado',
            field=models.CharField(choices=[('kernighan_lin', 'Kernighan-Lin'), ('current', 'Kernighan-Lin (Current)'), ('kmeans', 'K-Means Clustering'), ('voronoi', 'Voronoi Diagram'), ('random', 'Random Division'), ('dbscan', 'DBSCAN Clustering'), ('spectral', 'Spectral Clustering')], default='kernighan_lin', help_text='Algoritmo utilizado para dividir la ruta', max_length=20),
        ),
        migrations.AlterField(
            model_name='coloniaprocesada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=core.storage.StaticMediaStorage(), upload_to='colonias/imagenes/'),
        ),
    ]
